

create table category (
  id bigint generated by default as identity primary key,
  parent_id int,
  ort int,
  title text,
  icon text,
  is_used int,
  level int
);

create table site (
  id bigint generated by default as identity primary key,
  category_id int ,
  title text,
  url text,
  icon text,
  description text,
  is_used int default 1
);

create table users (
  id bigint generated by default as identity primary key,
  username text,
  password text
);

insert into
  users (username, password)
values
  ('admin', '123456');



#创建function 用于递归查询分类
create or replace function children(category) returns setof category as $$
  select * from category where parent_id = $1.id
$$ stable language sql;

create or replace function father(category) returns setof category rows 1 as $$
   select * from category where $1.parent_id = id
$$ stable language sql;