create table category (
  id bigint generated by default as identity primary key,
  parent_id bigint default 0,
  name text not null,
  en_name text,
  icon text,
  sort int not null default 10000
);

create table site (
  id bigint generated by default as identity primary key,
  category_id bigint not null references category(id) on delete restrict,
  title text not null,
  url text not null,
  logo text,
  logotype int not null default 1,
  description text,
  sort int not null default 10000,
  is_used int default 1
);

create or replace function children(category) returns setof category as $$
  select * from category where parent_id = $1.id order by sort asc, id asc
$$ stable language sql;

create or replace function father(category) returns setof category rows 1 as $$
  select * from category where $1.parent_id = id
$$ stable language sql;

alter table category enable row level security;
alter table site enable row level security;

create policy "Public category read"
  on category for select
  to anon, authenticated
  using (true);

create policy "Authenticated category insert"
  on category for insert
  to authenticated
  with check (auth.role() = 'authenticated');

create policy "Authenticated category update"
  on category for update
  to authenticated
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

create policy "Authenticated category delete"
  on category for delete
  to authenticated
  using (auth.role() = 'authenticated');

create policy "Public site read"
  on site for select
  to anon, authenticated
  using (true);

create policy "Authenticated site insert"
  on site for insert
  to authenticated
  with check (auth.role() = 'authenticated');

create policy "Authenticated site update"
  on site for update
  to authenticated
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

create policy "Authenticated site delete"
  on site for delete
  to authenticated
  using (auth.role() = 'authenticated');
