create table category (
  id bigint generated by default as identity primary key,
  parent_id int,
  name text,
  en_name text,
  icon text,
  sort int default 10000
);

create table site (
  id bigint generated by default as identity primary key,
  category_id int references category(id) ,
  title text,
  url text,
  logo text,
  logotype int default 1,
  description text,
  sort int default 10000
);

create table users (
  id bigint generated by default as identity primary key,
  username text,
  password text
);

insert into
  users (username, password)
values
  ('admin', '123456');




create or replace function children(category) returns setof category as $$
  select * from category where parent_id = $1.id
$$ stable language sql;

create or replace function father(category) returns setof category rows 1 as $$
   select * from category where $1.parent_id = id
$$ stable language sql;